$(document).ready(()=>{
    $('.header').html(LOCALE_winre[1])
    $('.section_diagnostic > .header').html(LOCALE_winre[6])
    $('.section_advanced > .header').html(LOCALE_winre[10])
    $('.section_usedevice > .header').html(LOCALE_winre[17])
    $('#tile-continue > h5').html(LOCALE_winre[2])
    $('#tile-usedevice > h5').html(LOCALE_winre[3])
    $('#tile-diagnostic > h5').html(LOCALE_winre[4])
    $('#tile-turnoffpc > h5').html(LOCALE_winre[5])
    $('#tile-recover > h5').html(LOCALE_winre[7])
    $('#tile-reset > h5').html(LOCALE_winre[8])
    $('#tile-advanced > h5').html(LOCALE_winre[9])
    $('#tile-restorepoint > h5').html(LOCALE_winre[11])
    $('#tile-image > h5').html(LOCALE_winre[12])
    $('#tile-bootrecover > h5').html(LOCALE_winre[13])
    $('#tile-cmd > h5').html(LOCALE_winre[14])
    $('#tile-uefi > h5').html(LOCALE_winre[15])
    $('#tile-bootparams > h5').html(LOCALE_winre[16])
    $('#tile-continue > h6').html(LOCALE_winre[18])
    $('#tile-usedevice > h6').html(LOCALE_winre[19])
    $('#tile-diagnostic > h6').html(LOCALE_winre[20])
    $('#tile-recover > h6').html(LOCALE_winre[21])
    $('#tile-reset > h6').html(LOCALE_winre[22])
    $('#tile-restorepoint > h6').html(LOCALE_winre[23])
    $('#tile-image > h6').html(LOCALE_winre[24])
    $('#tile-bootrecover > h6').html(LOCALE_winre[25])
    $('#tile-cmd > h6').html(LOCALE_winre[26])
    $('#tile-uefi > h6').html(LOCALE_winre[27])
    $('#tile-bootparams > h6').html(LOCALE_winre[28])
})