$(document).ready(()=>{
    $('#ControlContentMainPage .leftrow div:nth-child(1) h2').html(LOCALE_control[2]['MainPage'][1])
    $('#ControlContentMainPage .leftrow div:nth-child(1) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][2])
    $('#ControlContentMainPage .leftrow div:nth-child(1) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][3])
    $('#ControlContentMainPage .leftrow div:nth-child(1) span:nth-child(5)').html(LOCALE_control[2]['MainPage'][4])
    $('#ControlContentMainPage .leftrow div:nth-child(2) h2').html(LOCALE_control[2]['MainPage'][5])
    $('#ControlContentMainPage .leftrow div:nth-child(2) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][6])
    $('#ControlContentMainPage .leftrow div:nth-child(2) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][8])
    $('#ControlContentMainPage .leftrow div:nth-child(3) h2').html(LOCALE_control[2]['MainPage'][9])
    $('#ControlContentMainPage .leftrow div:nth-child(3) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][10])
    $('#ControlContentMainPage .leftrow div:nth-child(3) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][11])
    $('#ControlContentMainPage .leftrow div:nth-child(4) h2').html(LOCALE_control[2]['MainPage'][12])
    $('#ControlContentMainPage .leftrow div:nth-child(4) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][13])
    $('#ControlContentMainPage .rightrow div:nth-child(1) h2').html(LOCALE_control[2]['MainPage'][14])
    $('#ControlContentMainPage .rightrow div:nth-child(1) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][15])
    $('#ControlContentMainPage .rightrow div:nth-child(1) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][16])
    $('#ControlContentMainPage .rightrow div:nth-child(2) h2').html(LOCALE_control[2]['MainPage'][17])
    $('#ControlContentMainPage .rightrow div:nth-child(2) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][18])
    $('#ControlContentMainPage .rightrow div:nth-child(2) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][19])
    $('#ControlContentMainPage .rightrow div:nth-child(2) span:nth-child(5)').html(LOCALE_control[2]['MainPage'][20])
    $('#ControlContentMainPage .rightrow div:nth-child(3) h2').html(LOCALE_control[2]['MainPage'][21])
    $('#ControlContentMainPage .rightrow div:nth-child(3) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][22])
    $('#ControlContentMainPage .rightrow div:nth-child(3) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][23])
    $('#ControlContentMainPage .rightrow div:nth-child(3) span:nth-child(5)').html(LOCALE_control[2]['MainPage'][24])
    $('#ControlContentMainPage .rightrow div:nth-child(4) h2').html(LOCALE_control[2]['MainPage'][25])
    $('#ControlContentMainPage .rightrow div:nth-child(4) span:nth-child(1)').html(LOCALE_control[2]['MainPage'][26])
    $('#ControlContentMainPage .rightrow div:nth-child(4) span:nth-child(3)').html(LOCALE_control[2]['MainPage'][27])
})