$(document).ready(()=>{
    $('#OOBE_Page1 h1').html(LOCALE_oobe[1])
    $('#OOBE_Page1 h2 span:nth-child(1)').html(LOCALE_oobe[2])
    $('#OOBE_Page1 h2 span:nth-child(2)').html(LOCALE_oobe[3])
    $('#OOBE_Page1 h2 span:nth-child(3)').html(LOCALE_oobe[4])
    $('#OOBE_Page1 h2 span:nth-child(4)').html(LOCALE_oobe[5])
    $('#OOBE_Page2 h1').html(LOCALE_oobe[6])
    $('#OOBE_Page2 p.selectcolor').html(LOCALE_oobe[7])
    $('#OOBE_Page2 p.pcname').html(LOCALE_oobe[8])
    $('#OOBE_Page2 input').attr('placeholder', LOCALE_oobe[9])
    $('#OOBE_Page2 button').html(LOCALE_oobe[10])
    $('#OOBE_Page3 h1').html(LOCALE_oobe[11])
    $('#OOBE_Page3 h2').html(LOCALE_oobe[12])
    $('#OOBE_Page3 p.textUseStandart').html(LOCALE_oobe[13])
    $('#OOBE_Page3 ul').html(LOCALE_oobe[14])
    $('#OOBE_Page3 button.EditSettings').html(LOCALE_oobe[16])
    $('#OOBE_Page3 button.UseStandart').html(LOCALE_oobe[15])
    $('#OOBE_Page4 h1').html(LOCALE_oobe[17])
    $('#OOBE_Page4 p.ifyouwantapassword').html(LOCALE_oobe[18])
    $('#OOBE_Page4 table tr:nth-child(1) input').attr('placeholder', LOCALE_oobe[19])
    $('#OOBE_Page4 table tr:nth-child(1) p').html(LOCALE_oobe[20])
    $('#OOBE_Page4 table tr:nth-child(2) p').html(LOCALE_oobe[21])
    $('#OOBE_Page4 table tr:nth-child(3) p').html(LOCALE_oobe[22])
    $('#OOBE_Page4 table tr:nth-child(4) p').html(LOCALE_oobe[23])
    $('#OOBE_Page4 button').html(LOCALE_oobe[24])
    $('#OOBE_Page5 h2 span').html(LOCALE_oobe[25])
})